export const servers = [
  {
    id: "general",
    name: "General",
    icon: "🌟",
    color: "from-blue-400 to-cyan-400",
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "🎮",
    color: "from-purple-400 to-pink-400",
  },
  {
    id: "music",
    name: "Music",
    icon: "🎵",
    color: "from-green-400 to-blue-400",
  },
  {
    id: "tech",
    name: "Tech",
    icon: "💻",
    color: "from-orange-400 to-red-400",
  },
];

export const channels = [
  { id: "general", name: "general", type: "text" },
  { id: "random", name: "random", type: "text" },
];

export const messages = [
  {
    id: 1,
    user: "Alex",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Hey everyone! How's it going?",
    time: "2:30 PM",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    user: "Sarah",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Just finished working on a new project. Excited to share it!",
    time: "2:32 PM",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    user: "Mike",
    avatar: "/placeholder.svg?height=32&width=32",
    message:
      "That sounds awesome! Can't wait to see what you've been working on.",
    time: "2:35 PM",
    color: "from-green-500 to-blue-500",
  },
  {
    id: 4,
    user: "Emma",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Anyone up for a gaming session later tonight?",
    time: "2:40 PM",
    color: "from-orange-500 to-red-500",
  },
  {
    id: 5,
    user: "David",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Sure, I'm in! What game are we playing?",
    time: "2:45 PM",
    color: "from-yellow-500 to-green-500",
  },
  {
    id: 6,
    user: "Sophia",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I just tried a new recipe today and it turned out amazing!",
    time: "2:50 PM",
    color: "from-pink-500 to-purple-500",
  },
  {
    id: 7,
    user: "James",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Did anyone catch the game last night? What a comeback!",
    time: "2:53 PM",
    color: "from-red-500 to-yellow-500",
  },
  {
    id: 8,
    user: "Mia",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Can't wait for the weekend. Need some rest and relaxation.",
    time: "2:55 PM",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: 9,
    user: "Oliver",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Working on a cool open-source project, anyone interested?",
    time: "3:00 PM",
    color: "from-green-500 to-teal-500",
  },
  {
    id: 10,
    user: "Lily",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I'm planning a trip to Japan next month. Any travel tips?",
    time: "3:05 PM",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: 11,
    user: "Noah",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Just started learning guitar! Any advice for beginners?",
    time: "3:10 PM",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 12,
    user: "Ava",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I recommend practicing daily, even if just 10 minutes!",
    time: "3:12 PM",
    color: "from-pink-500 to-red-500",
  },
  {
    id: 13,
    user: "Ethan",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Anyone up for a virtual movie night this Friday?",
    time: "3:15 PM",
    color: "from-blue-500 to-purple-500",
  },
  {
    id: 14,
    user: "Isabella",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Sounds fun! What movie are we watching?",
    time: "3:17 PM",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: 15,
    user: "Lucas",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "How about a classic sci-fi? Maybe Blade Runner?",
    time: "3:20 PM",
    color: "from-green-500 to-lime-500",
  },
  {
    id: 16,
    user: "Charlotte",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Count me in! I love sci-fi classics.",
    time: "3:25 PM",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 17,
    user: "Benjamin",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Don't forget to bring snacks! 🍿",
    time: "3:27 PM",
    color: "from-red-500 to-orange-500",
  },
  {
    id: 18,
    user: "Amelia",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I’ll make some popcorn and drinks. Virtual party!",
    time: "3:30 PM",
    color: "from-pink-500 to-purple-500",
  },
  {
    id: 19,
    user: "Elijah",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Does anyone have recommendations for good podcasts?",
    time: "3:35 PM",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: 20,
    user: "Harper",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I like true crime and history podcasts. 'Serial' is great!",
    time: "3:37 PM",
    color: "from-green-500 to-teal-500",
  },
  {
    id: 21,
    user: "Michael",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Anyone tried the new VR game? It's insane!",
    time: "3:40 PM",
    color: "from-yellow-500 to-red-500",
  },
  {
    id: 22,
    user: "Evelyn",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Not yet, but I’m planning to. Heard great reviews.",
    time: "3:42 PM",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: 23,
    user: "Daniel",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Let's schedule a gaming night to try it out together.",
    time: "3:45 PM",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 24,
    user: "Grace",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I'm in! Let me know the time.",
    time: "3:47 PM",
    color: "from-pink-500 to-purple-500",
  },
  {
    id: 25,
    user: "Matthew",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Anyone interested in a weekend hiking trip?",
    time: "3:50 PM",
    color: "from-green-500 to-lime-500",
  },
  {
    id: 26,
    user: "Chloe",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Count me in! I love being outdoors.",
    time: "3:52 PM",
    color: "from-orange-500 to-red-500",
  },
  {
    id: 27,
    user: "Jacob",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "What trails are we thinking about?",
    time: "3:55 PM",
    color: "from-yellow-500 to-green-500",
  },
  {
    id: 28,
    user: "Ella",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "I recommend the Blue Ridge Trail; beautiful views!",
    time: "3:57 PM",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 29,
    user: "Logan",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Also, pack some extra water and snacks!",
    time: "4:00 PM",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: 30,
    user: "Samantha",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Looking forward to it! I'll bring my camera too.",
    time: "4:05 PM",
    color: "from-pink-500 to-red-500",
  },
];

export const activeUsers = [
  {
    id: 1,
    name: "Alex",
    status: "online",
    avatar: "/placeholder.svg?height=32&width=32",
    activity: "Playing Spotify",
  },
  {
    id: 2,
    name: "Sarah",
    status: "online",
    avatar: "/placeholder.svg?height=32&width=32",
    activity: "Coding",
  },
  {
    id: 3,
    name: "Mike",
    status: "away",
    avatar: "/placeholder.svg?height=32&width=32",
    activity: "Away",
  },
  {
    id: 4,
    name: "Emma",
    status: "online",
    avatar: "/placeholder.svg?height=32&width=32",
    activity: "Gaming",
  },
  {
    id: 5,
    name: "David",
    status: "dnd",
    avatar: "/placeholder.svg?height=32&width=32",
    activity: "Do Not Disturb",
  },
];

export const dmContacts = [
  {
    id: 1,
    name: "Jessica",
    avatar: "/placeholder.svg?height=32&width=32",
    status: "online",
    lastMessage: "See you tomorrow!",
  },
  {
    id: 2,
    name: "Ryan",
    avatar: "/placeholder.svg?height=32&width=32",
    status: "away",
    lastMessage: "Thanks for the help",
  },
  {
    id: 3,
    name: "Lisa",
    avatar: "/placeholder.svg?height=32&width=32",
    status: "online",
    lastMessage: "How was your day?",
  },
];
